name = "wallet-cloudflare"
type = "webpack"

account_id = "f014c6e7add3694d80b4e0b4a237eb45"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-29"
kv_namespaces = [ 
 { binding = "WALLET", id = "2d7ec8d3cfaf4bb9847178f646801de8" ,preview_id="2d7ec8d3cfaf4bb9847178f646801de8" }
]